### ISSUE TITLE
Does not work with current Chrome version (83), says only version 80 is supported

### ISSUE THREAD

**Issue by bergmeister** [adamdriscoll/selenium-powershell#97]
I just did in PowerShell 7:
```pwsh
Install-Module Selenium
$Driver = Start-SeChrome -Incognito
```
I got this
```
Starting ChromeDriver 80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}) on port 61987
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

DevTools listening on ws://127.0.0.1:61992/devtools/browser/9416af12-ed71-4fcf-a7ca-d85375767393
New-Object: C:\Users\christoph.bergmeiste\Documents\PowerShell\Modules\Selenium\3.0.0\Selenium.psm1:252
Line |
 252 |  …   $Driver = New-Object -TypeName "OpenQA.Selenium.Chrome.ChromeDriver …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling ".ctor" with "2" argument(s): "session not created: This version of ChromeDriver
     | only supports Chrome version 80 (SessionNotCreated)"

```

`Get-Error` report:
```
Type           : System.Management.Automation.CmdletInvocationException
ErrorRecord    :
    Exception             :
        Type           : System.Management.Automation.MethodInvocationException
        ErrorRecord    :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Exception calling ".ctor" with "2" argument(s): "session not created: This version of
ChromeDriver only supports Chrome version 80 (SessionNotCreated)"
                HResult : -2146233087
            CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : DotNetconstructorTargetInvocation
        TargetSite     :
            Name          : AuxiliaryConstructorInvoke
            DeclaringType : System.Management.Automation.DotNetAdapter, System.Management.Automation, Version=7.1.0.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35
            MemberType    : Method
            Module        : System.Management.Automation.dll
        StackTrace     :
   at System.Management.Automation.DotNetAdapter.AuxiliaryConstructorInvoke(MethodInformation methodInformation,
Object[] arguments, Object[] originalArguments)
   at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors,
Object[] arguments)
   at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors,
Object[] args)
        Message        : Exception calling ".ctor" with "2" argument(s): "session not created: This version of
ChromeDriver only supports Chrome version 80 (SessionNotCreated)"
        InnerException :
            Type       : System.InvalidOperationException
            TargetSite :
                Name          : UnpackAndThrowOnError
                DeclaringType : OpenQA.Selenium.Remote.RemoteWebDriver
                MemberType    : Method
                Module        : WebDriver
            StackTrace :
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan
commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options)
            Message    : session not created: This version of ChromeDriver only supports Chrome version 80
(SessionNotCreated)
            Source     : WebDriver
            HResult    : -2146233079
        Source         : System.Management.Automation
        HResult        : -2146233087
    CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
    InvocationInfo        :
        MyCommand        : New-Object
        ScriptLineNumber : 252
        OffsetInLine     : 19
        HistoryId        : 43
        ScriptName       : C:\Users\christoph.bergmeiste\Documents\PowerShell\Modules\Selenium\3.0.0\Selenium.psm1
        Line             : $Driver = New-Object -TypeName "OpenQA.Selenium.Chrome.ChromeDriver" -ArgumentList
$service,$Chrome_Options

        PositionMessage  : At
C:\Users\christoph.bergmeiste\Documents\PowerShell\Modules\Selenium\3.0.0\Selenium.psm1:252 char:19
                           + …   $Driver = New-Object -TypeName "OpenQA.Selenium.Chrome.ChromeDriver …
                           +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        PSScriptRoot     : C:\Users\christoph.bergmeiste\Documents\PowerShell\Modules\Selenium\3.0.0
        PSCommandPath    : C:\Users\christoph.bergmeiste\Documents\PowerShell\Modules\Selenium\3.0.0\Selenium.psm1
        InvocationName   : New-Object
        CommandOrigin    : Internal
    ScriptStackTrace      : at Start-SeChrome<Process>,
C:\Users\christoph.bergmeiste\Documents\PowerShell\Modules\Selenium\3.0.0\Selenium.psm1: line 252
                            at <ScriptBlock>, <No file>: line 1
TargetSite     :
    Name          : Invoke
    DeclaringType : System.Management.Automation.Runspaces.PipelineBase, System.Management.Automation,
Version=7.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    MemberType    : Method
    Module        : System.Management.Automation.dll
StackTrace     :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown,
ExecutionOptions options)
Message        : Exception calling ".ctor" with "2" argument(s): "session not created: This version of ChromeDriver
only supports Chrome version 80 (SessionNotCreated)"
Data           : System.Collections.ListDictionaryInternal
InnerException :
    Type           : System.Management.Automation.MethodInvocationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling ".ctor" with "2" argument(s): "session not created: This version of
ChromeDriver only supports Chrome version 80 (SessionNotCreated)"
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : DotNetconstructorTargetInvocation
    TargetSite     :
        Name          : AuxiliaryConstructorInvoke
        DeclaringType : System.Management.Automation.DotNetAdapter, System.Management.Automation, Version=7.1.0.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace     :
   at System.Management.Automation.DotNetAdapter.AuxiliaryConstructorInvoke(MethodInformation methodInformation,
Object[] arguments, Object[] originalArguments)
   at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors,
Object[] arguments)
   at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors,
Object[] args)
    Message        : Exception calling ".ctor" with "2" argument(s): "session not created: This version of
ChromeDriver only supports Chrome version 80 (SessionNotCreated)"
    InnerException :
        Type       : System.InvalidOperationException
        TargetSite :
            Name          : UnpackAndThrowOnError
            DeclaringType : OpenQA.Selenium.Remote.RemoteWebDriver
            MemberType    : Method
            Module        : WebDriver
        StackTrace :
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan
commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options)
        Message    : session not created: This version of ChromeDriver only supports Chrome version 80
(SessionNotCreated)
        Source     : WebDriver
        HResult    : -2146233079
    Source         : System.Management.Automation
    HResult        : -2146233087
Source         : System.Management.Automation
HResult        : -2146233087
```

**Comment by Filipp0vAP** [comment]
Hello!

I faced the same problem. But this is not a module problem.
You just need to download the new version of the web driver http://chromedriver.chromium.org/downloads 
and replace it in this folder C:\Program Files\WindowsPowerShell\Modules\Selenium\3.0.0\assemblies
If you installed the module in another folder, you need to replace it there

**Comment by bergmeister** [comment]
Thanks for the info. Given that the module ships with those dependencies, it definitely is a module problem. Some apparently made that change recently, the module just needs re-publishing for now but clearly needs a better mechanism to update dependencies...
https://github.com/adamdriscoll/selenium-powershell/pull/88

**Comment by adamdriscoll** [comment]
I've just published an updated module that works with the latest chrome and I agree we need a better way to update the drivers. It's annoying to have to check that all the time. Need something automated . Let's open another issue on that.
